config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :profiles
  resources :articles do
    resources :comments
  end
  root 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  belongs_to :profile
  validates :title, presence: true
  validates :text, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @articles=Article.all.order(created_at: :desc)

  end

  def show
    @article = Article.find params[:id]
    @comments = @article.comments
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find params[:id]
  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find params[:id]
    if @article.update article_params
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find params[:id]
    @article.destroy
    redirect_to articles_path
  end
  private
  def article_params
    params.require(:article).permit(:title, :text, :profile_id) #article is only part of the total param set
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<tr>
  <td><%=link_to article.title.to_s, article_path(article)%></td>
  <td>by: <%=link_to profile_by_id(article.profile_id).pen_name, profile_path(profile_by_id article.profile_id)%></td>
  <td><%= article.created_at%></td>
</tr>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation">
    <ul>
      <%@article.errors.full_messages.each do |explanation|%>
        <li><%=explanation%></li>
      <%end%>
    </ul>
  </div>
<%end%>

<%=form_with model: @article, local: true do |form|%>
  <p>
    <%=form.label :title%>
    <%=form.text_field :title%>
  </p>
  <p>
    <%=form.label :text%>
    <%=form.text_area :text%>
  </p>
  <%= form.hidden_field :profile_id, value: current_profile.id %>
  <p>
    <%=form.submit%>
  </p>
<%end%>

app/views/articles/edit.html.erb
<h2>edit article</h2>

<%= render 'form'%>

app/views/articles/index.html.erb
consider reading some articles, or
<%= link_to 'create a new article!', new_article_path%>

<table>
  <%=render @articles%>
</table>

app/views/articles/new.html.erb
<h2>Make a new article</h2>

<%=render 'form'%>

app/views/articles/show.html.erb
<h2><%= @article.title%></h2>
<p>author: <%=link_to profile_by_id(@article.profile_id).pen_name, profile_path(profile_by_id @article.profile_id)%></p>
<p>
  <%=@article.created_at%>
  <%if current_user && current_profile.id==@article.profile_id%>
  <%= link_to 'delete', article_path(@article), method: :delete, data: {confirm: 'do you want to delete this article? This action cannot be undone'}%>
  <%= link_to 'edit', edit_article_path(@article)%>
  <%end%>
</p>
<p><%= @article.text %></p>

<h2>Comments</h2>
<p><%= render 'comments/form'%></p>
<p><%=  render partial:'comments/comment', collection: @comments %></p>